### ISSUE TITLE
Add support for additional styles like dim, strikeout, etc

### ISSUE THREAD

**Issue by arash-rohani** [termbox/termbox2#56] opened 2023-05-06 00:12 UTC
Looking at the colors and attributes, 

I can see:
bold, underline, reverse, italic, and blink

but no:
dim, strikeout, double underline, overline, and any bright equivalents to the normal colors

How come they aren't implemented? I especially needed dimming for my application but was surprised that the attribute is not there.

Are there any plans to implement these in the future?

**Comment by adsr** [comment] 2023-05-06 01:18
Hello, it's relatively simple to add a new cap[^1]. The problem is we only have room for 2 more caps in our bit-field. (Unless we move up to a 64-bit `intattr_t`. Then we'd have room for plenty more but only in the truecolor build.)

Among dim, strikeout, double underline, etc, if there are two that are generally useful and supported on a good number of terminal emulators, we could choose to support them.

I checked `man 5 terminfo` for the other caps you mentioned but didn't see them. They may be under different names. If they're not in terminfo, they'd have to be hard-coded like we do for modified arrow keys or mouse caps.

If you come up with a list of the cap names (or raw escape codes), we can do a quick analysis and see how broadly each cap is supported and decide from there.

To get around the bit-field limitation and allow some flexibility, we could potentially reserve one of the last 2 bits as something you can configure at runtime, e.g.:

```c
// TB_CUST_DIM, TB_CUST_STRIKEOUT, TB_CUST_DOUBLE_UNDERLINE
tb_set_custom_cap(TB_CUST_DIM);
tb_print(0, 0, TB_CUST, 0, "this is dim");
```

[^1]: If you have a terminfo package installed with `infocmp` on your `PATH`, you can, for example, add `dim` [here](https://github.com/termbox/termbox2/blob/f72cef0e3ba0ba2978e4ae5404e15f05e94b9cb3/codegen.sh#L52) and then run `make terminfo format`. From there's it's just a few more lines of code to add a `TB_DIM` bit field.

**Comment by arash-rohani** [comment] 2023-05-06 04:07
Hi.
These are the escape codes for the mentioned attributes:
dim                     \033[2m
invisible               \033[8m
strikeout              \033[9m
double underline  \033[21m
overline               \033[53m

And the bright colors are +40 to the normal color (e.g. bright red fg = \033[91m)

I tested these with `echo -e` in both Lxterminal and Alacritty. Alacritty doesn't support overline and double underline but does support the rest. Lxterminal supports all of them.

I then added dim like you suggested and ran `make terminfo format`. Then added the rest of the code (attr_dim, TB_DIM, TB_TRUECOLOR_DIM, ...).

Now there's a problem: the dim attribute works in Alacritty but not in Lxterminal. I checked the header file and even set "\033[2m" to some of the terminal caps that showed blank for the dim attribute (eterm, rxvt-unicode, rxvt-256color) just to be safe but Lxterminal still doesn't dim the text.

I don't know what the problem is because as I mentioned above, Lxterminal should support dim.

**Comment by arash-rohani** [comment] 2023-05-06 09:39
I experimented a little bit and it seems like some terminals have this problem where in truecolor mode the dim doesn't work but in normal mode it does:
    Lxterminal
    Gnome-terminal
    Xfce4-terminal
And some could actually dim the text in both modes:
    Alacritty
    Wezterm
    Xterm

**Comment by arash-rohani** [comment] 2023-05-09 03:14
I was being stupid. I forgot to test the terminals with different color codes via echo. I was only testing dim with \033[XXm colors in the mentioned terminals and that is equivalent to the normal color mode. When I tested the terminals with \033[38;2;XXX;XXX;XXXm (truecolor) colors they behaved exactly the same as termbox did.
It also turns out that some of the terminals cannot dim when in 256 color mode (\033[38;5;XXXm) but some can. This has nothing to do with termbox and is actually the limitation of the terminal.

Should I close this issue or is it better to leave it open in case someone decides to officially add the missing attributes (or at least dim attribute) to termbox?

**Comment by zachallaun** [comment] 2023-05-14 14:33
To add an additional opinion: of the unimplemented capabilities, I believe dim and bright are both useful and widely supported (in my somewhat limited experience building TUIs).

I’m also very curious about the option/work involved in moving to 64-bit attrs. I’m not well versed in these matters, but I’m curious whether there are significant trade-offs. More room to continue supporting modern formatting seems like a worthwhile change that would extend the life of termbox2.

**Comment by arash-rohani** [comment] 2023-05-15 02:57
@zachallaun I've been poking around the code and if you are willing to break compatibility, there are loads of things that can be improved, simplified, or cleaned up very easily.
 
As far as I can tell there is no actual need to typedef `uintattr_t` to a smaller type (`uint16_t`) when `TB_OPT_TRUECOLOR` is not defined. There's no need to keep two different definitions of the attributes like `TB_BOLD` and `TB_TRUECOLOR_BOLD`. If you remove them you can simplify and clean up a lot of the code and free up even more flags for non-truecolor modes like a bright flag that doesn't work on truecolor but can work on normal mode. And default color should really come back as a flag and not 0.

For example if you define the flags like this you can dedicate `0x100` up to `TB_DEFAULT` to the flags that don't work in truecolor. And any flags from `TB_DEFAULT` up can work on all modes (if the terminal supports them).

```c
#define TB_BRIGHT    0x100 /* not for truecolor */
#define TB_XXX       0x200 /* not for truecolor */
#define TB_DEFAULT   0x01000000
#define TB_BOLD      0x02000000
#define TB_UNDERLINE 0x04000000
#define TB_REVERSE   0x08000000
#define TB_ITALIC    0x10000000
#define TB_BLINK     0x20000000
#define TB_DIM       0x40000000
```

And now all you have to do is change `send_attr()` and `send_sgr()` to deal with it.

**Comment by adsr** [comment] 2023-05-15 05:43
The reason for using `uint16_t`s is explained [here](https://github.com/termbox/termbox2/pull/25#issuecomment-1146438291). I find that users of termbox tend to fall into one of two groups: (1) people writing new software for vintage hardware, or (2) people interested in modern terminal behavior who want a simpler API than ncurses. It's a balancing act (which requires ifdefs). The original termbox project splintered into many forks because it did not cater to group (2).

We can for sure add a compile-time option to define `uintattr_t` as `uint64_t`. Under that ifdef we can define all these extras. How's that sound?

> `#define TB_DEFAULT   0x01000000`

I've gone back and forth on whether default should be a high bit or 0. High bit is more correct but not as simple or convenient or intuitive as 0. I tend to favor simplicity. Default==0 breaks only when you're trying to emit black in 256- or true-color mode, which I suspect is uncommon in practice. See [this commit](https://github.com/termbox/termbox2/commit/1eaa24be68b432fd54f587c6ef365562abaac99f) and [this comment](https://github.com/termbox/termbox2/issues/51#issuecomment-1493485122) for info on why I changed it back to 0.

**Comment by arash-rohani** [comment] 2023-05-15 06:43
@adsr I say put a flag for the old (16-bit) hardware that disables truecolor and sets the attributes to 16 bit but set the default to 32bit (64 bit only when more attributes are implemented). Either way `TB_TRUECOLOR_` attributes should be removed in my opinion. For example:

```c
#ifdef TB_OPT_16BIT
    typedef uint16_t uintattr_t; 
    #define TB_DEFAULT   0x0100
    #define TB_BOLD      0x0200
    #define TB_UNDERLINE 0x0400
    #define TB_REVERSE   0x0800
    #define TB_ITALIC    0x1000
    #define TB_BLINK     0x2000
    #define TB_DIM       0x4000
#else
    typedef uint32_t uintattr_t; 
    #define TB_DEFAULT   0x01000000
    #define TB_BOLD      0x02000000
    #define TB_UNDERLINE 0x04000000
    #define TB_REVERSE   0x08000000
    #define TB_ITALIC    0x10000000
    #define TB_BLINK     0x20000000
    #define TB_DIM       0x40000000
#endif
```
I've read the reasoning for the default change but I disagree. As you've mentioned in #51 this doesn't fix any other colors from being displayed incorrectly. I think the correct way to handle the problem would've been the first thing you suggested as the remedy:

> 1. Document that callers should ensure sane tb_set_clear_attrs after calling tb_set_output_mode.

I think we should also document that after any output mode change you should probably redraw everything with the new colors and not just new clear attributes.

> Default==0 breaks only when you're trying to emit black in 256- or true-color mode, which I suspect is uncommon in practice

I don't think it's uncommon. If I wanted pure black in truecolor I'd certainly go with 0x000000 and not `TB_TRUECOLOR_BLACK`.

**Comment by zachallaun** [comment] 2023-05-15 11:53
Thank you both for the additional information!

@adsr I’m certainly in camp (2), and more specifically I’m hoping to modernize [ex_termbox](https://github.com/ndreynolds/ex_termbox), a FFI for Elixir, which doesn’t have accessible low-level terminal support built in (raw mode). This seems like a common use-case for termbox based on the readme as well! For this case, simplicity is certainly king (to minimize the amount of glue code required to interface), but “feature completeness” is also very useful. 

That also means that it doesn’t affect me whether things are hidden behind flags/etc. We‘ll set whatever flags we need in wrapper code and be good to go.

**Comment by zachallaun** [comment] 2023-05-15 11:54
Thank you both for the additional information!

@adsr I’m certainly in camp (2), and more specifically I’m hoping to modernize [ex_termbox](https://github.com/ndreynolds/ex_termbox), a FFI for Elixir, which doesn’t have accessible low-level terminal support built in (raw mode). This seems like a common use-case for termbox based on the readme as well! For this case, simplicity is certainly king (to minimize the amount of glue code required to interface), but “feature completeness” is also very useful. 

That also means that it doesn’t affect me whether things are hidden behind flags/etc. We‘ll set whatever flags we need in wrapper code and be good to go.

**Comment by adsr** [comment] 2023-05-17 02:42
> @adsr I say put a flag for the old (16-bit) hardware that disables truecolor and sets the attributes to 16 bit but set the default to 32bit (64 bit only when more attributes are implemented).

If we did a poll of all termbox users and the majority voted this way, I'd agree. In absence of that, I have to go by my personal correspondence with termbox users. The majority of users who I've been in touch with do not fall into this camp. Remember termbox was born out of the suckless community who are ruthless minimalists. I don't intend for this to be an argument from authority, just my raw observation. For that reason I prefer keeping it opt-in for features that will consume more resources (however small).

> Either way TB_TRUECOLOR_ attributes should be removed in my opinion. For example:

I like this idea. Will look into this.

> > Default==0 breaks only when you're trying to emit black in 256- or true-color mode, which I suspect is uncommon in practice
> 
> I don't think it's uncommon. If I wanted pure black in truecolor I'd certainly go with 0x000000 and not TB_TRUECOLOR_BLACK.

To me, being able to memset the entire back/front buffer to 0 and having a bitfield that defaults at value 0 together outweigh the one case of wanting to emit the color black. Emitting black or white IMO is kind of risky because many terminals default to white-on-black or black-on-white or something close. You can of course emit both a fg and opposite bg, but then I believe you're in special territory. I can't think of many serious CLI programs that change the bg by default or at all.

All that said, as I said I've gone back and forth on this one. It's not as correct, but I do believe it's simpler and more intuitive in most but not all cases.

> @adsr I’m certainly in camp (2), and more specifically I’m hoping to modernize [ex_termbox](https://github.com/ndreynolds/ex_termbox), a FFI for Elixir, which doesn’t have accessible low-level terminal support built in (raw mode)

Excellent. If you're writing a wrapper around the dynamic library, that already builds with everything enabled, so any extras we add like dimming etc will get into that build as well. (See [this comment](https://github.com/termbox/termbox2/issues/39#issuecomment-1204792403).)

Does Elixir/Erlang have anything like FFI? I encourage you to submit a PR to the `demo/` folder if so.

**Comment by zachallaun** [comment] 2023-05-17 16:52
> Does Elixir/Erlang have anything like FFI? I encourage you to submit a PR to the demo/ folder if so.

It does, but it's unfortunately a bit more verbose than most of what's in `demo/`. Once I get things working, I'll see if there's a minimal example that would make sense!

**Comment by adsr** [comment] 2023-07-13 07:24
Added in fcb8dc5. Thank you all for the input.

**Closed by adsr** 2023-07-13 07:24 UTC

**Comment by zachallaun** [comment] 2023-07-13 11:26
Thank you for continuing to maintain and improve this project!
